[build-system]
requires = ["hatchling","hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "a405"
description = "atsc405 code"
authors = [
  { name="Philip Austin", email="paustin@eoas.ubc.ca" },
]
dynamic = ["version"]

[project.scripts]
killprocs = "a405.utils.killprocs:main"
killjobs = "a405.utils.killjobs:main"
pyncdump = "a405.utils.ncdump:main"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/a405/_version.py"

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64"]
authors = ["Phil Austin <paustin@eos.ubc.ca>"]
name = "a405lib"
preview = ["pixi-build"]

[tool.pixi.dependencies]
python = ">3.12"
numpy = "*"
scipy = "*"
pip = "*"
zarr = "*"
git = "*"
jupyterlab = "*"
jupyterlab-myst = "*"
jupytext = "*"
pythia-datasets = "*"
metpy = "*"
netcdf4 = "*"
hatch = ">=1.16.3,<2"
ghp-import = ">=2.1.0,<3"
pytz = ">=2025.2,<2026"

[tool.pixi.pypi-dependencies]
a405 = { path = ".", editable = true }
gradelib = { path = "/Users/phil/repos/gradelib", editable = true }

[tool.pixi.tasks]
